### ISSUE TITLE
Not work on new version of meteor

### ISSUE THREAD

**Issue by hmelenok** [gadicc/meteor-rest-test#1]
Had want to try your repo for meteor REST service 

``` bash
[[[[[ ~/Documents/meteor-rest-test ]]]]]

=> Started proxy.

=> Meteor 1.0 is out! Visit www.meteor.com for all the details.

   Meteor 1.0 is being downloaded in the background. You can update to
   it by running 'meteor update'.

=> Meteor 1.0.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

While building the application:
error: no such package: 'npm'

=> Your application has errors. Waiting for file change.
```

after update

``` bash
$ meteor update
Installing Meteor 1.0.1:
 * 'meteor' build tool (version 381da7e862)

This project is at the latest release which is compatible with your             
current package constraints.

/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
                        throw(ex);
                              ^
Error: unknown package: npm
    at throwConstraintSolverError (packages/constraint-solver/resolver.js:246)
    at ConstraintSolver.Resolver.resolve (packages/constraint-solver/resolver.js:193)
    at ConstraintSolver.PackagesResolver.resolve (packages/constraint-solver/constraint-solver.js:263)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/catalog.js:327:32
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:338:18
    at _.extend.withValue (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:331:34
    at _.extend.withValue (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:329:23
    at _.extend.withValue (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.enterJob (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:303:26)
    at _.extend.resolveConstraints (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/catalog.js:320:30)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:1965:36
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:250:13
    at _.extend.withValue (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:243:29
    at _.extend.withValue (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:241:18
    at _.extend.withValue (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:232:23
    at _.extend.withValue (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:112:14)
    at Object.capture (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:231:19)
    at main.registerCommand.name [as func] (/Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/commands-packages.js:1964:31)
    at /Users/hmelenok/.meteor/packages/meteor-tool/.1.0.36.1ucd9cj++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/main.js:1353:23
```

**Comment by hmelenok** [comment]
Sorry for issue: 
- `./.meteor/packages` in line with  `npm` change to `meteorhacks:npm` and re run `meteor update` ~2 times
- And changes in `./meteor-rest.js` : 

``` javascript
//var connect = Meteor.require('connect');
//var Fiber = Meteor.require('fibers');
var connect = Meteor.npmRequire('connect');
var Fiber = Meteor.npmRequire('fibers');
```
